[workspace]
members=["crates/moond-sys", "crates/agc-interp", "crates/agc-isa", "crates/agc-driver", "crates/agc-asm", "crates/agc-crosstest"]
resolver="3"

[workspace.package]
description = "Moon landing emulator designed for the future"
license-file = "COPYING.md"

[workspace.dependencies]
bindgen = "0.71.0"
cc = "^1.0.83"