//! C source-code backend for the AGC recompiler.
//!
//! Emits a single C translation unit containing:
//! - An `#include "agc_runtime.h"` or an inlined copy of the runtime header.
//! - One `agc_run(AgcState *s)` function holding all recompiled basic blocks.
//! - Each basic block as a labelled sequence of C statements derived directly
//!   from the instruction's [`SemOp`] sequence.
//! - Direct branches: `goto bb_XXXXXX;`
//! - Indirect branches: `switch(s->z)` over the known target set.

use alloc::format;
use alloc::string::{String, ToString};

use agc_isa::{Cond, Dest, Expr, Flag, SemOp};
use agc_isa::InstrType;

use crate::backend::Backend;
use crate::ir::{InstrStream, Terminator};

// ─── Runtime header ───────────────────────────────────────────────────────────

/// Embedded C runtime header.  Included verbatim when `inline_runtime = true`.
pub static RUNTIME_HEADER: &str = r#"/* agc_runtime.h — AGC Block-2 recompiler runtime
 * Generated by agc-recompile.  Ones-complement arithmetic helpers + state. */
#ifndef AGC_RUNTIME_H
#define AGC_RUNTIME_H
#include <stdint.h>

/* ── Return codes ────────────────────────────────────────────────────────── */
#define AGC_OK        0   /* normal termination of a block sequence         */
#define AGC_HALT      1   /* no further recompiled code at current s->z     */
#define AGC_DISPATCH  2   /* indirect branch; caller re-dispatches on s->z  */

/* ── CPU state ───────────────────────────────────────────────────────────── */
typedef struct AgcState {
    uint16_t a;         /* accumulator (16-bit; bit15 = overflow)           */
    uint16_t l;         /* L register (15-bit)                              */
    uint16_t q;         /* Q / return-address register (15-bit)             */
    uint16_t eb;        /* erasable bank (3-bit)                            */
    uint16_t fb;        /* fixed bank (5-bit)                               */
    uint16_t z;         /* program counter (15-bit)                         */
    uint16_t bb;        /* both banks (derived: FB<<3 | EB)                 */
    uint16_t tmp;       /* non-addressable temporary register               */
    uint8_t  extend;    /* EXTEND flip-flop                                 */
    uint8_t  inhint;    /* interrupt-inhibit flag                           */
    /* Memory / I/O callbacks */
    uint16_t (*mem_read )(struct AgcState *, uint16_t addr);
    void     (*mem_write)(struct AgcState *, uint16_t addr, uint16_t val);
    uint16_t (*chan_read )(struct AgcState *, uint16_t ch);
    void     (*chan_write)(struct AgcState *, uint16_t ch,  uint16_t val);
} AgcState;

/* ── Ones-complement arithmetic ──────────────────────────────────────────── */

static inline uint16_t oc_neg(uint16_t x) {
    return (uint16_t)((~x) & 0x7FFFU);
}

static inline uint16_t oc_add(uint16_t a, uint16_t b) {
    uint32_t r = (uint32_t)(a & 0x7FFFU) + (uint32_t)(b & 0x7FFFU);
    if (r >= 0x8000U) r -= 0x7FFFU;
    return (uint16_t)(r & 0x7FFFU);
}

static inline uint16_t oc_sub(uint16_t a, uint16_t b) {
    return oc_add(a, oc_neg(b));
}

static inline int32_t oc15_to_i32(uint16_t w) {
    w &= 0x7FFFU;
    if ((w & 0x4000U) == 0U) return (int32_t)w;
    if (w == 0x7FFFU)        return 0;
    return -((int32_t)((~w) & 0x7FFFU));
}

static inline uint16_t i32_to_oc15(int32_t n) {
    if (n >= 0) return (uint16_t)(n > 0x3FFF ? 0x3FFF : n);
    int32_t m = (-n) > 0x3FFF ? 0x3FFF : (-n);
    return (uint16_t)((~(uint32_t)m) & 0x7FFFU);
}

/* OC 15-bit × 15-bit — high and low 15-bit result words. */
static inline uint16_t oc_mul_hi(uint16_t a, uint16_t b) {
    int64_t p = (int64_t)oc15_to_i32(a) * (int64_t)oc15_to_i32(b);
    return i32_to_oc15((int32_t)(p >> 15));
}
static inline uint16_t oc_mul_lo(uint16_t a, uint16_t b) {
    int64_t p = (int64_t)oc15_to_i32(a) * (int64_t)oc15_to_i32(b);
    return i32_to_oc15((int32_t)(p & 0x7FFFL));
}

/* OC divide: (a_hi, a_lo) / divisor → quotient or remainder. */
static inline uint16_t oc_div_q(uint16_t a_hi, uint16_t a_lo, uint16_t divisor) {
    int64_t hi  = (int64_t)oc15_to_i32(a_hi);
    int64_t lo  = (int64_t)(oc15_to_i32(a_lo) < 0 ? -oc15_to_i32(a_lo) : oc15_to_i32(a_lo));
    int64_t div = (int64_t)oc15_to_i32(divisor);
    if (div == 0) return 0;
    return i32_to_oc15((int32_t)(((hi << 15) | lo) / div));
}
static inline uint16_t oc_div_r(uint16_t a_hi, uint16_t a_lo, uint16_t divisor) {
    int64_t hi  = (int64_t)oc15_to_i32(a_hi);
    int64_t lo  = (int64_t)(oc15_to_i32(a_lo) < 0 ? -oc15_to_i32(a_lo) : oc15_to_i32(a_lo));
    int64_t div = (int64_t)oc15_to_i32(divisor);
    if (div == 0) return 0;
    return i32_to_oc15((int32_t)(((hi << 15) | lo) % div));
}

/* High word of double-precision OC addition (a_hi,a_lo) + (b_hi,b_lo). */
static inline uint16_t dp_add_hi(uint16_t a_hi, uint16_t a_lo,
                                  uint16_t b_hi, uint16_t b_lo) {
    uint32_t lo_raw = (uint32_t)(a_lo & 0x7FFFU) + (uint32_t)(b_lo & 0x7FFFU);
    uint16_t carry = (lo_raw >= 0x8000U) ? 1U : 0U;
    return oc_add(oc_add(a_hi, b_hi), carry);
}

/* ── Augment / Diminish / Saturate ──────────────────────────────────────── */

static inline int is_plus_zero(uint16_t w)  { return (w & 0x7FFFU) == 0x0000U; }
static inline int is_minus_zero(uint16_t w) { return (w & 0x7FFFU) == 0x7FFFU; }
static inline int is_negative(uint16_t w)   { return ((w & 0x4000U) != 0U) && !is_minus_zero(w); }
static inline int is_positive(uint16_t w)   { return !is_plus_zero(w) && ((w & 0x4000U) == 0U); }
static inline int is_zero_or_neg(uint16_t w){ return is_plus_zero(w) || is_minus_zero(w) || is_negative(w); }
static inline int has_overflow(uint16_t w)  { return ((w >> 14) & 3U) == 1U || ((w >> 14) & 3U) == 2U; }

static inline uint16_t oc_aug(uint16_t w) {
    w &= 0x7FFFU;
    if (is_plus_zero(w) || is_minus_zero(w)) return w;
    return is_positive(w) ? oc_add(w, 1U) : oc_add(w, 0x7FFEU);
}

static inline uint16_t oc_dim(uint16_t w) {
    w &= 0x7FFFU;
    if (is_plus_zero(w) || is_minus_zero(w)) return w;
    if (is_positive(w)) return (w == 1U) ? 0x0000U : (uint16_t)(w - 1U);
    uint16_t m = ((~w) & 0x7FFFU);
    return (m == 1U) ? 0x7FFFU : (uint16_t)((~((m - 1U) & 0x7FFFU)) & 0x7FFFU);
}

static inline uint16_t oc_sat(uint16_t a) {
    uint16_t b14 = (a >> 14) & 1U, b15 = (a >> 15) & 1U;
    if (!b15 &&  b14) return 0x3FFFU; /* positive overflow */
    if ( b15 && !b14) return 0x4000U; /* negative overflow */
    return a & 0x7FFFU;
}

/* ── Memory helpers (thin wrappers — callbacks handle banking) ──────────── */
#define agc_mem_read(s, a)       ((s)->mem_read ((s), (a)))
#define agc_mem_write(s, a, v)   ((s)->mem_write((s), (a), (v)))
#define agc_chan_read(s, c)       ((s)->chan_read ((s), (c)))
#define agc_chan_write(s, c, v)  ((s)->chan_write((s), (c), (v)))

#endif /* AGC_RUNTIME_H */
"#;

// ─── C backend ────────────────────────────────────────────────────────────────

/// Options for the C backend.
#[derive(Debug, Clone)]
pub struct CBackendOptions {
    /// Embed the runtime header inline rather than emitting `#include`.
    pub inline_runtime: bool,
    /// Name for the emitted entry function (default: `"agc_run"`).
    pub function_name: String,
}

impl Default for CBackendOptions {
    fn default() -> Self {
        CBackendOptions {
            inline_runtime: true,
            function_name: "agc_run".into(),
        }
    }
}

/// The C source-code backend.
pub struct CBackend {
    pub options: CBackendOptions,
}

impl Default for CBackend {
    fn default() -> Self { CBackend { options: CBackendOptions::default() } }
}

impl Backend for CBackend {
    type Output = String;
    type Error = String;

    fn emit(&self, stream: &InstrStream) -> Result<String, String> {
        let mut out = String::new();

        // Header / preamble.
        if self.options.inline_runtime {
            out.push_str(RUNTIME_HEADER);
            out.push('\n');
        } else {
            out.push_str("#include \"agc_runtime.h\"\n\n");
        }

        let fn_name = &self.options.function_name;
        out.push_str(&format!("int {fn_name}(AgcState *s) {{\n"));

        // Top-level dispatch switch — re-entry point for indirect branches.
        out.push_str("    /* entry dispatch */\n");
        out.push_str("    switch (s->z) {\n");
        for &addr in stream.blocks.keys() {
            out.push_str(&format!("        case 0x{addr:04x}U: goto bb_{addr:05o};\n"));
        }
        out.push_str("        default: return AGC_HALT;\n");
        out.push_str("    }\n\n");

        // Emit each basic block.
        for (&_addr, block) in &stream.blocks {
            let label = block.label;
            out.push_str(&format!("bb_{label:05o}:  /* 0o{label:07o} */\n"));

            for rec in &block.instrs {
                // Instruction comment.
                out.push_str(&format!(
                    "    /* 0o{:07o}: {} 0o{:07o} */\n",
                    rec.pc, rec.mnemonic, rec.operand
                ));

                // Emit C statements for each SemOp.
                let next_pc = (rec.pc + 1) & 0x7FFF;
                let ctx = EmitCtx {
                    pc: rec.pc,
                    next_pc,
                    operand: rec.operand,
                    instr_word: rec.raw_word,
                    instr_type: rec.instr_type,
                    indirect_targets: &stream.indirect_targets,
                };

                for op in &rec.ops {
                    emit_sem_op(op, &ctx, &mut out);
                }
            }

            // Terminator.
            emit_terminator(&block.terminator, &stream.indirect_targets, &mut out);
            out.push('\n');
        }

        out.push_str("}\n");
        Ok(out)
    }
}

// ─── Emission context ─────────────────────────────────────────────────────────

#[allow(dead_code)]
struct EmitCtx<'a> {
    pc: u16,
    next_pc: u16,
    operand: u16,
    instr_word: u16,
    instr_type: InstrType,
    indirect_targets: &'a alloc::collections::BTreeSet<u16>,
}

// ─── SemOp → C ───────────────────────────────────────────────────────────────

fn emit_sem_op(op: &SemOp, ctx: &EmitCtx<'_>, out: &mut String) {
    match op {
        SemOp::Set(dest, expr) => {
            let rhs = expr_to_c(expr, ctx);
            let lhs = dest_to_c(dest, ctx);
            out.push_str(&format!("    {lhs} = {rhs};\n"));
        }
        SemOp::SetFlag(Flag::Extend) => out.push_str("    s->extend = 1;\n"),
        SemOp::ClearFlag(Flag::Extend) => out.push_str("    s->extend = 0;\n"),
        SemOp::SetFlag(Flag::Inhint) => out.push_str("    s->inhint = 1;\n"),
        SemOp::ClearFlag(Flag::Inhint) => out.push_str("    s->inhint = 0;\n"),
        // Branch / BranchIf are handled by the terminator emitter.
        // Emitting a z-update here keeps `s->z` consistent for indirect dispatch.
        SemOp::Branch(expr) => {
            let target_c = expr_to_c(expr, ctx);
            out.push_str(&format!("    s->z = {target_c};\n"));
        }
        SemOp::BranchIf(cond, expr) => {
            let cond_c = cond_to_c(cond, ctx);
            let target_c = expr_to_c(expr, ctx);
            // Determine the static target for a direct goto (if resolvable).
            if let Some(target) = static_expr_target(expr, ctx) {
                out.push_str(&format!(
                    "    if ({cond_c}) {{ s->z = {target_c}; goto bb_{target:05o}; }}\n"
                ));
            } else {
                out.push_str(&format!(
                    "    if ({cond_c}) {{ s->z = {target_c}; {indirect_dispatch} }}\n",
                    indirect_dispatch = make_indirect_dispatch(ctx.indirect_targets)
                ));
            }
        }
    }
}

fn emit_terminator(
    term: &Terminator,
    indirect_targets: &alloc::collections::BTreeSet<u16>,
    out: &mut String,
) {
    match term {
        Terminator::FallThrough(addr) => {
            out.push_str(&format!("    goto bb_{addr:05o};\n"));
        }
        Terminator::Jump(addr) => {
            out.push_str(&format!("    goto bb_{addr:05o};\n"));
        }
        Terminator::CondBranch { taken, fallthru } => {
            // The condition and s->z assignment was already emitted by
            // emit_sem_op for the BranchIf op; here we only emit the
            // unconditional fall-through for the not-taken path.
            out.push_str(&format!("    goto bb_{fallthru:05o}; /* not taken */\n"));
            let _ = taken; // taken path handled by emit_sem_op BranchIf
        }
        Terminator::CcsBranch(_targets) => {
            // All four arms emitted as BranchIf statements by emit_sem_op.
            // The CCS instruction's semantics guarantee exactly one arm fires.
            out.push_str("    /* CCS: all arms covered by BranchIf above */\n");
            out.push_str("    return AGC_HALT;\n");
        }
        Terminator::Indirect { possible_targets } => {
            let targets: &alloc::collections::BTreeSet<u16> = indirect_targets;
            // Combine the possible_targets from the terminator with the
            // global indirect_targets set (they may differ for TC vs NDX).
            let combined: alloc::collections::BTreeSet<u16> = targets
                .iter()
                .chain(possible_targets.iter())
                .copied()
                .collect();
            if combined.is_empty() {
                out.push_str("    return AGC_DISPATCH;\n");
            } else {
                out.push_str("    switch (s->z) {\n");
                for &t in &combined {
                    out.push_str(&format!(
                        "        case 0x{t:04x}U: goto bb_{t:05o};\n"
                    ));
                }
                out.push_str("        default: return AGC_DISPATCH;\n");
                out.push_str("    }\n");
            }
        }
        Terminator::Halt => {
            out.push_str("    return AGC_HALT;\n");
        }
    }
}

// ─── Expression → C string ───────────────────────────────────────────────────

fn expr_to_c(expr: &Expr, ctx: &EmitCtx<'_>) -> String {
    match expr {
        Expr::Lit(n)    => format!("0x{:04x}U", n),
        Expr::A         => "s->a".into(),
        Expr::L         => "s->l".into(),
        Expr::Q         => "s->q".into(),
        // Z is the already-advanced PC; we know it statically.
        Expr::Z         => format!("0x{:04x}U", ctx.next_pc),
        Expr::Tmp       => "s->tmp".into(),
        Expr::Mem       => format!("agc_mem_read(s, 0x{:04x}U)", ctx.operand),
        Expr::MemHi     => format!("agc_mem_read(s, 0x{:04x}U)", ctx.operand.wrapping_add(1) & 0x7FFF),
        Expr::Channel   => format!("agc_chan_read(s, 0x{:04x}U)", ctx.operand),
        Expr::Operand   => format!("0x{:04x}U", ctx.operand),
        Expr::PcRel(n)  => {
            let t = (ctx.next_pc as i32 + *n as i32) as u16 & 0x7FFF;
            format!("0x{t:04x}U")
        }
        Expr::MemAt(a)  => format!("agc_mem_read(s, 0x{a:04x}U)"),
        Expr::Deref(e)  => {
            let inner = expr_to_c(e, ctx);
            format!("agc_mem_read(s, {inner})")
        }
        Expr::InstrWord => format!("0x{:04x}U", ctx.instr_word),

        // Ones-complement arithmetic.
        Expr::OcAdd(a, b) => format!("oc_add({}, {})", expr_to_c(a, ctx), expr_to_c(b, ctx)),
        Expr::OcSub(a, b) => format!("oc_sub({}, {})", expr_to_c(a, ctx), expr_to_c(b, ctx)),
        Expr::OcNeg(x)    => format!("oc_neg({})", expr_to_c(x, ctx)),

        // Bitwise.
        Expr::And(a, b) => format!("({} & {})", expr_to_c(a, ctx), expr_to_c(b, ctx)),
        Expr::Or(a, b)  => format!("({} | {})", expr_to_c(a, ctx), expr_to_c(b, ctx)),
        Expr::Xor(a, b) => format!("({} ^ {})", expr_to_c(a, ctx), expr_to_c(b, ctx)),
        Expr::Not(x)    => format!("(~{})", expr_to_c(x, ctx)),

        // Double-precision — mul/div return via out-params; we need a helper macro.
        // We emit a call to a statement-expression wrapper to stay within a single expression.
        Expr::MulHi(a, b) => format!(
            "oc_mul_hi({}, {})",
            expr_to_c(a, ctx), expr_to_c(b, ctx)
        ),
        Expr::MulLo(a, b) => format!(
            "oc_mul_lo({}, {})",
            expr_to_c(a, ctx), expr_to_c(b, ctx)
        ),
        Expr::DivQ(hi, lo, div) => format!(
            "oc_div_q({}, {}, {})",
            expr_to_c(hi, ctx), expr_to_c(lo, ctx), expr_to_c(div, ctx)
        ),
        Expr::DivR(hi, lo, div) => format!(
            "oc_div_r({}, {}, {})",
            expr_to_c(hi, ctx), expr_to_c(lo, ctx), expr_to_c(div, ctx)
        ),
        Expr::DpAddHi(ah, al, bh, bl) => format!(
            "dp_add_hi({},{},{},{})",
            expr_to_c(ah, ctx), expr_to_c(al, ctx),
            expr_to_c(bh, ctx), expr_to_c(bl, ctx)
        ),

        // Augment / Diminish / Saturate.
        Expr::Augment(x)  => format!("oc_aug({})",  expr_to_c(x, ctx)),
        Expr::Diminish(x) => format!("oc_dim({})",  expr_to_c(x, ctx)),
        Expr::Saturate(x) => format!("oc_sat({})",  expr_to_c(x, ctx)),
    }
}

// ─── Destination → C lvalue ──────────────────────────────────────────────────

fn dest_to_c(dest: &Dest, ctx: &EmitCtx<'_>) -> String {
    match dest {
        Dest::A       => "s->a".into(),
        Dest::L       => "s->l".into(),
        Dest::Q       => "s->q".into(),
        Dest::Z       => "s->z".into(),
        Dest::Tmp     => "s->tmp".into(),
        Dest::Mem     => format!("*agc_mem_lval(s, 0x{:04x}U)", ctx.operand),
        Dest::MemHi   => format!("*agc_mem_lval(s, 0x{:04x}U)", ctx.operand.wrapping_add(1) & 0x7FFF),
        Dest::Channel => format!("*agc_chan_lval(s, 0x{:04x}U)", ctx.operand),
        Dest::MemAt(a) => format!("*agc_mem_lval(s, 0x{a:04x}U)"),
        Dest::Deref(e) => {
            let inner = expr_to_c(e, ctx);
            format!("*agc_mem_lval(s, {inner})")
        }
    }
}

// ─── Condition → C boolean expression ────────────────────────────────────────

fn cond_to_c(cond: &Cond, ctx: &EmitCtx<'_>) -> String {
    match cond {
        Cond::IsPositive(e)  => format!("is_positive({})",  expr_to_c(e, ctx)),
        Cond::IsPlusZero(e)  => format!("is_plus_zero({})", expr_to_c(e, ctx)),
        Cond::IsNegative(e)  => format!("is_negative({})",  expr_to_c(e, ctx)),
        Cond::IsMinusZero(e) => format!("is_minus_zero({})",expr_to_c(e, ctx)),
        Cond::IsZeroOrNeg(e) => format!("is_zero_or_neg({})", expr_to_c(e, ctx)),
        Cond::HasOverflow(e) => format!("has_overflow({})",  expr_to_c(e, ctx)),
        Cond::And(a, b)      => format!("({} && {})", cond_to_c(a, ctx), cond_to_c(b, ctx)),
        Cond::Not(x)         => format!("(!{})", cond_to_c(x, ctx)),
    }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/// Attempt to resolve an expression to a static branch target address.
fn static_expr_target(expr: &Expr, ctx: &EmitCtx<'_>) -> Option<u16> {
    match expr {
        Expr::Lit(n)   => Some(*n & 0x7FFF),
        Expr::PcRel(n) => Some((ctx.next_pc as i32 + *n as i32) as u16 & 0x7FFF),
        Expr::Z        => Some(ctx.next_pc),
        Expr::Operand  => Some(ctx.operand & 0x7FFF),
        _ => None,
    }
}

/// Emit a C indirect-dispatch fragment (switch over all known targets).
fn make_indirect_dispatch(targets: &alloc::collections::BTreeSet<u16>) -> String {
    if targets.is_empty() {
        return "return AGC_DISPATCH;".into();
    }
    let mut s = "switch (s->z) { ".to_string();
    for &t in targets {
        s.push_str(&format!("case 0x{t:04x}U: goto bb_{t:05o}; "));
    }
    s.push_str("default: return AGC_DISPATCH; }");
    s
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::collections::BTreeSet;

    #[test]
    fn runtime_header_compiles_check() {
        // Just ensure the constant is non-empty and contains key symbols.
        assert!(RUNTIME_HEADER.contains("oc_add"));
        assert!(RUNTIME_HEADER.contains("AgcState"));
        assert!(RUNTIME_HEADER.contains("is_positive"));
    }

    #[test]
    fn empty_stream_emits_valid_c() {
        use crate::ir::InstrStream;
        use alloc::collections::BTreeMap;
        let stream = InstrStream {
            blocks: BTreeMap::new(),
            entry_points: alloc::vec![],
            indirect_targets: BTreeSet::new(),
        };
        let backend = CBackend::default();
        let src = backend.emit(&stream).unwrap();
        assert!(src.contains("int agc_run(AgcState *s)"));
        assert!(src.contains("switch (s->z)"));
        assert!(src.contains("return AGC_HALT"));
    }
}
